coverage:
    range: 50..75
    round: nearest
    precision: 2
    status:
        project:
            default:
                target: auto
                threshold: 10%
        patch:
            default:
                target: auto
                threshold: 10%

comment:
    layout: "reach, diff, flags, files"
    behavior: default
    require_changes: false  # if true: only post the comment if coverage changes
    require_base: no        # [yes :: must have a base report to post]
    require_head: yes       # [yes :: must have a head report to post]
